name: Build Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches-ignore:
      - '*'

jobs:
  build-and-push-amd:
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Tags
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          echo "SAFE_REF_NAME=${GITHUB_REF_NAME//\//-}" >>${GITHUB_ENV}
      - name: Login Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./docker/golang.Dockerfile
          tags: ghcr.io/${{ env.REPO_NAME }}:latest,ghcr.io/${{ env.REPO_NAME }}:latest-amd,ghcr.io/${{ env.REPO_NAME }}:${{ env.SAFE_REF_NAME }}-amd

  build-and-push-arm:
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Tags
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          echo "SAFE_REF_NAME=${GITHUB_REF_NAME//\//-}" >>${GITHUB_ENV}
      - name: Login Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./docker/golang.Dockerfile
          platforms: linux/arm64
          tags: ghcr.io/${{ env.REPO_NAME }}:latest-arm,ghcr.io/${{ env.REPO_NAME }}:${{ env.SAFE_REF_NAME }}-arm

  merge-manifest:
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [build-and-push-amd, build-and-push-arm]
    steps:
      - name: Prepare Tags
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          echo "SAFE_REF_NAME=${GITHUB_REF_NAME//\//-}" >>${GITHUB_ENV}
      - name: Login Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Create Versioned Manifest (${{ env.SAFE_REF_NAME }})
        run: |
          docker buildx imagetools create -t ghcr.io/${{ env.REPO_NAME }}:${{ env.SAFE_REF_NAME }} \
            ghcr.io/${{ env.REPO_NAME }}:${{ env.SAFE_REF_NAME }}-amd \
            ghcr.io/${{ env.REPO_NAME }}:${{ env.SAFE_REF_NAME }}-arm
      - name: Create Latest Manifest
        run: |
          docker buildx imagetools create -t ghcr.io/${{ env.REPO_NAME }}:latest \
            ghcr.io/${{ env.REPO_NAME }}:latest-amd \
            ghcr.io/${{ env.REPO_NAME }}:latest-arm